language: node_js
node_js:
  - "iojs"
  - "7"
before_script:
  - npm install -g gulp-cli
script: gulp
addons:
  sonarcloud:
    organization: "matsgemmeke-github" # the key of the org you chose at step #3
    token:
      secure: c2ad07a63823c4ccfe2d233c8463ac174d1143ba # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner