language: node_js
dist: trusty
node_js:
- node
addons:
  sonarcloud:
    organization: matsgemmeke-github
    token:
      secure: 45d53550e000c157800fac804a339d596cc96dee
deploy:
  provider: heroku
  api_key:
    secure: a5311202-6b40-4ae1-9eea-f23c39840e08
  app: seechange-server
  on:
    all_branches: true
before_script:
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
- npm install chai chai-http mocha
- npm install axios-mock-adapter --save-dev
- npm install
after_failure:
- cat MSBuild_*.failure.txt
after_success:
- npm run sonar-scanner
script:
- npm test
services:
- mongodb
